# .github/FUNDING.yml
github: [lerenard666]           # Ton handle GitHub Sponsors si activé
patreon: ezkali                 # ou laisse vide si pas de compte
open_collective: ezkali
ko_fi: ezkali
buy_me_a_coffee: ezkali
custom:
  - https://ezkali.net/support
  - https://ezkali.net/invest
  - https://ezkali.net/partners
  - https://ezkali.net/early-access
